export const GET_PRODUCTS = 'GET_PRODUCTS';
export const POST_PRODUCTS = 'POST_PRODUCTS';
export const POST_ALL_COLOR = 'POST_ALL_COLOR';
export const POST_ALL_SIZES = 'POST_ALL_SIZES';
export const GET_ALL_CATEGORIES = 'POST_ALL_CATEGORIES';
export const GET_ALL_SERIES = 'POST_ALL_SERIES';
