export const GET_PRODUCTS = 'GET_PRODUCTS';
export const POST_PRODUCTS = 'POST_PRODUCTS';
export const POST_ALL_COLOR = 'POST_ALL_COLOR';
export const GET_ALL_SIZES = 'GET_ALL_SIZES';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_SERIES = 'POST_ALL_SERIES';
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
