
export const GET_PRODUCTS = "GET_PRODUCTS";
export const POST_PRODUCTS = "POST_PRODUCTS";
export const GET_ALL_COLOR = "GET_ALL_COLOR";
export const GET_ALL_SIZES = "GET_ALL_SIZES";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_SERIES = "POST_ALL_SERIES";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS";
export const GET_USERS = "GET_USERS";
export const POST_USERS = "POST_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const PUT_USERS = "PUT_USERS";
export const POST_TO_CART = "POST_TO_CART";
export const GET_USER_CART = "GET_USER_CART";
export const SEND_MAIL = "SEND_MAIL";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_USER = "DELETE_CART_USER";
export const ADD_HISTORY = "ADD_HISTORY";
export const ADD_TO_FAVORITES="ADD_TO_FAVORITES"; 
export const REMOVE_FROM_FAVORITES="REMOVE_FROM_FAVORITES";
export const GET_ALL_FAV= "GET_ALL_FAV"
export const NOTIFY_STOCK = "NOTIFY_STOCK";
export const POST_REVIEWS = 'POST_REVIEWS';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_NAME = 'GET_USER_BY_NAME';
export const GET_REVIEW_BY_ID = 'GET_REVIEW_BY_ID';
export const GET_ALL_HISTORY= "GET_ALL_HISTORY";
export const POST_INFORMATION="POST_INFORMATION";
export const GET_LATEST_INFORMATION="GET_LATEST_INFORMATION";


